package rebue.area.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.area.mo.AreAreaMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface AreAreaMapper extends MybatisBaseMapper<AreAreaMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int insert(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int insertSelective(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    AreAreaMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int updateByPrimaryKeySelective(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int updateByPrimaryKey(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    List<AreAreaMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    List<AreAreaMo> selectSelective(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    boolean existSelective(AreAreaMo record);
}