package rebue.area.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.area.mo.AreAreaMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface AreAreaMapper extends MybatisBaseMapper<AreAreaMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int insert(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int insertSelective(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    AreAreaMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int updateByPrimaryKeySelective(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    int updateByPrimaryKey(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    List<AreAreaMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    List<AreAreaMo> selectSelective(AreAreaMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARE_AREA
     *
     * @mbg.generated 2018-04-02 15:53:41
     */
    boolean existSelective(AreAreaMo record);
    
    /**
     * 获取所有省份信息
     * Title: selectProvinceAll
     * Description: 
     * @return
     * @date 2018年4月6日 下午3:05:11
     */
    List<AreAreaMo> selectProvinceAll();
    
    /**
     * 根据上级区域编号获取所有下级区域信息
     * Title: selectCityAllByProvinceCode
     * Description: 
     * @param record
     * @return
     * @date 2018年4月6日 下午3:09:08
     */
    List<AreAreaMo> selectLowerAreaAll(AreAreaMo record);
    
    /**
     * 根据城市查询直辖镇信息
     * Title: selectCountyAllByCityCode
     * Description: 
     * @param record
     * @return
     * @date 2018年4月6日 下午3:22:21
     */
    List<AreAreaMo> selectCountyAllByCityCode(AreAreaMo record);
}